"""Injects ASRS cells into notebook 05."""
import json
from pathlib import Path

ROOT_NB = Path("c:/Users/ali/Desktop/Projet-INFO-2AS2")
NB_PATH = ROOT_NB / "notebooks" / "05_backtest_school_run.ipynb"

with open(NB_PATH, "r", encoding="utf-8") as f:
    nb = json.load(f)


def md(*lines):
    return {
        "cell_type": "markdown",
        "id": "",
        "metadata": {},
        "source": list(lines),
    }


def code(*lines):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": "",
        "metadata": {},
        "outputs": [],
        "source": list(lines),
    }


# ── Cell 29: ASRS header ───────────────────────────────────────────────────────
c29 = md(
    "---\n",
    "## 11. Advanced School Run Strategy (ASRS)\n",
    "\n",
    "**Timeframe** : 5-minute bars  \n",
    "**Signal bar**: 4th candle after DAX open (opens 09:15 CET, closes 09:20)  \n",
    "**5th bar fallback**: use bar opening 09:20 when 4th bar is narrow or wick-heavy  \n",
    "**Entry**: Buy stop = signal_high + 2 pts | Sell stop = signal_low − 2 pts  \n",
    "**Stop loss**: Opposite order price (risk = full bar range + 4 pts)  \n",
    "**No profit target** — position runs until stopped out or EOD (17:30 CET)  \n",
    "\n",
    "> Data source: Capital.com API (epic: `DE40`, `MINUTE_5`).  \n",
    "> Run **Cell 11a** to collect/refresh 5-min DAX data before running the backtest.\n",
)

# ── Cell 30: 5-min DAX data collection ────────────────────────────────────────
c30_lines = [
    "# ─── 11a. Collect 5-min DAX morning data via Capital.com API ────\n",
    "# Re-run this cell to update data. Days already in file are skipped.\n",
    "import os, time\n",
    "from datetime import datetime, timedelta, timezone\n",
    "from dotenv import load_dotenv\n",
    "\n",
    "load_dotenv(ROOT / '.env')\n",
    "\n",
    "DAX5M_PATH = ROOT / 'data' / 'dax-5m.csv'\n",
    "\n",
    "def _parse_candles_5m(prices):\n",
    "    rows = []\n",
    "    for p in prices:\n",
    "        ts = pd.Timestamp(p['snapshotTimeUTC'], tz='UTC').tz_convert('Europe/Berlin')\n",
    "        rows.append({\n",
    "            'datetime': ts,\n",
    "            'open':   (p['openPrice']['bid']  + p['openPrice']['ask'])  / 2,\n",
    "            'high':   (p['highPrice']['bid']  + p['highPrice']['ask'])  / 2,\n",
    "            'low':    (p['lowPrice']['bid']   + p['lowPrice']['ask'])   / 2,\n",
    "            'close':  (p['closePrice']['bid'] + p['closePrice']['ask']) / 2,\n",
    "            'volume': p['lastTradedVolume'],\n",
    "        })\n",
    "    return pd.DataFrame(rows).set_index('datetime')\n",
    "\n",
    "# Load existing data\n",
    "if DAX5M_PATH.exists():\n",
    "    dax5m_existing = pd.read_csv(DAX5M_PATH, index_col='datetime', parse_dates=True)\n",
    "    if dax5m_existing.index.tz is None:\n",
    "        dax5m_existing.index = dax5m_existing.index.tz_localize('Europe/Berlin')\n",
    "    last_saved_date = dax5m_existing.index.max().date()\n",
    "    print(f'Existing data: {len(dax5m_existing):,} bars up to {last_saved_date}')\n",
    "else:\n",
    "    dax5m_existing = pd.DataFrame()\n",
    "    last_saved_date = None\n",
    "    print('No existing 5-min data file — will collect from scratch.')\n",
    "\n",
    "API_KEY    = os.getenv('CAPITAL_API_KEY')\n",
    "IDENTIFIER = os.getenv('CAPITAL_IDENTIFIER')\n",
    "PASSWORD   = os.getenv('CAPITAL_PASSWORD')\n",
    "\n",
    "if not (API_KEY and IDENTIFIER and PASSWORD):\n",
    "    print('WARNING: API credentials not found in .env')\n",
    "    print('Set CAPITAL_API_KEY, CAPITAL_IDENTIFIER, CAPITAL_PASSWORD to collect data.')\n",
    "    dax5m = dax5m_existing.copy() if not dax5m_existing.empty else None\n",
    "else:\n",
    "    from src.service.collector.session_manager import SessionManager\n",
    "    from src.service.collector.api_client import CapitalClient\n",
    "\n",
    "    _session = SessionManager(API_KEY, IDENTIFIER, PASSWORD)\n",
    "    _client  = CapitalClient(_session)\n",
    "\n",
    "    EPIC           = 'DE40'\n",
    "    RESOLUTION     = 'MINUTE_5'\n",
    "    # Collect 08:45–11:30 UTC = covers 09:00–13:30 CET (first 4h of DAX session)\n",
    "    SESSION_START  = '08:45'\n",
    "    SESSION_END    = '11:30'\n",
    "    SLEEP          = 0.5\n",
    "\n",
    "    today      = datetime.now(timezone.utc).date()\n",
    "    end_date   = today - timedelta(days=1)\n",
    "    start_date = (last_saved_date + timedelta(days=1)) if last_saved_date else (today - timedelta(days=1500))\n",
    "\n",
    "    business_days = pd.bdate_range(str(start_date), str(end_date)).date.tolist()\n",
    "    print(f'Days to collect: {len(business_days)}')\n",
    "\n",
    "    all_frames = []\n",
    "    for day in business_days:\n",
    "        day_str = str(day)\n",
    "        frm_iso = f'{day_str}T{SESSION_START}:00'\n",
    "        to_iso  = f'{day_str}T{SESSION_END}:00'\n",
    "        try:\n",
    "            raw_prices = _client.get_candles_range(EPIC, frm_iso, to_iso, resolution=RESOLUTION)\n",
    "            if raw_prices.get('prices'):\n",
    "                df_day = _parse_candles_5m(raw_prices['prices'])\n",
    "                all_frames.append(df_day)\n",
    "        except Exception as e:\n",
    "            print(f'  {day_str}: {e}')\n",
    "        time.sleep(SLEEP)\n",
    "\n",
    "    if all_frames:\n",
    "        df_new = pd.concat(all_frames)\n",
    "        df_new = df_new[~df_new.index.duplicated(keep='first')]\n",
    "        if not dax5m_existing.empty:\n",
    "            dax5m = pd.concat([dax5m_existing, df_new]).sort_index()\n",
    "            dax5m = dax5m[~dax5m.index.duplicated(keep='first')]\n",
    "        else:\n",
    "            dax5m = df_new.sort_index()\n",
    "        dax5m.to_csv(DAX5M_PATH)\n",
    "        print(f'Saved {len(dax5m):,} bars to {DAX5M_PATH.name}')\n",
    "    else:\n",
    "        print('No new bars collected.')\n",
    "        dax5m = dax5m_existing.copy() if not dax5m_existing.empty else None\n",
    "\n",
    "if dax5m is None or (isinstance(dax5m, pd.DataFrame) and dax5m.empty):\n",
    "    print('No 5-min data available. Provide API credentials and re-run.')\n",
    "    dax5m = None\n",
    "else:\n",
    "    print(f'5-min DAX data ready: {len(dax5m):,} bars | '\n",
    "          f'{dax5m.index[0].date()} → {dax5m.index[-1].date()}')\n",
    "    display(dax5m.head(3))\n",
]
c30 = code(*c30_lines)

# ── Cell 31: ASRS parameters ──────────────────────────────────────────────────
c31_md = md(
    "## 11b. ASRS Parameters\n",
)
c31 = code(
    "# ─── ASRS Strategy parameters ───────────────────────────────\n",
    "ASRS_ENTRY_BUFFER = 2      # pts beyond signal bar high/low\n",
    "ASRS_NARROW_RANGE = 15     # 4th bar range below this → use 5th bar\n",
    "ASRS_WICK_RATIO   = 0.60   # (upper+lower wick) / range > this → use 5th bar\n",
    "ASRS_EOD_EXIT     = '17:30'  # CET\n",
    "ASRS_ENTRY_CUTOFF = '11:00'  # no new entries after 2h of DAX session (CET)\n",
    "\n",
    "BAR4_TIME = '09:15'   # 4th 5-min bar opens at 09:15 CET\n",
    "BAR5_TIME = '09:20'   # 5th 5-min bar opens at 09:20 CET\n",
    "\n",
    "print('ASRS Parameters set:')\n",
    "print(f'  Entry buffer   : ±{ASRS_ENTRY_BUFFER} pts')\n",
    "print(f'  Narrow range   : < {ASRS_NARROW_RANGE} pts  → 5th bar fallback')\n",
    "print(f'  Wick ratio     : > {ASRS_WICK_RATIO:.0%}  → 5th bar fallback')\n",
    "print(f'  EOD exit       : {ASRS_EOD_EXIT} CET')\n",
    "print(f'  Entry cutoff   : {ASRS_ENTRY_CUTOFF} CET (2h after open)')\n",
)

# ── Cell 32: Signal bar identification ────────────────────────────────────────
c32_md = md("## 11c. Signal Bar Identification (4th bar + 5th bar fallback)\n")
c32 = code(
    "# ─── Select ASRS signal bar for each trading day ─────────────\n",
    "\n",
    "def _is_wick_heavy(o, h, l, c, threshold=ASRS_WICK_RATIO):\n",
    "    bar_range = h - l\n",
    "    if bar_range < 1:\n",
    "        return True\n",
    "    body = abs(c - o)\n",
    "    return (bar_range - body) / bar_range > threshold\n",
    "\n",
    "\n",
    "def select_asrs_signal_bars(df_5m):\n",
    "    \"\"\"\n",
    "    For each trading day identify the ASRS signal bar.\n",
    "    Returns DataFrame indexed by date with one row per tradeable day.\n",
    "    \"\"\"\n",
    "    if df_5m is None or df_5m.empty:\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    idx = df_5m.index\n",
    "    if idx.tz is None:\n",
    "        idx = idx.tz_localize('Europe/Berlin')\n",
    "    else:\n",
    "        idx = idx.tz_convert('Europe/Berlin')\n",
    "    df = df_5m.copy()\n",
    "    df.index = idx\n",
    "\n",
    "    bar4 = df[df.index.strftime('%H:%M') == BAR4_TIME].copy()\n",
    "    bar5 = df[df.index.strftime('%H:%M') == BAR5_TIME].copy()\n",
    "    bar4['_date'] = bar4.index.date\n",
    "    bar5['_date'] = bar5.index.date\n",
    "    bar4 = bar4.set_index('_date')\n",
    "    bar5 = bar5.set_index('_date')\n",
    "\n",
    "    records = []\n",
    "    for date in bar4.index:\n",
    "        b4 = bar4.loc[date]\n",
    "        o4, h4, l4, c4 = b4['open'], b4['high'], b4['low'], b4['close']\n",
    "        range4 = h4 - l4\n",
    "\n",
    "        use_bar5 = (\n",
    "            (range4 < ASRS_NARROW_RANGE or _is_wick_heavy(o4, h4, l4, c4))\n",
    "            and date in bar5.index\n",
    "        )\n",
    "\n",
    "        b   = bar5.loc[date] if use_bar5 else b4\n",
    "        num = 5 if use_bar5 else 4\n",
    "        reason = ('narrow' if range4 < ASRS_NARROW_RANGE else 'wicks') if use_bar5 else None\n",
    "\n",
    "        records.append({\n",
    "            'sig_high'       : b['high'],\n",
    "            'sig_low'        : b['low'],\n",
    "            'sig_open'       : b['open'],\n",
    "            'sig_close'      : b['close'],\n",
    "            'sig_range'      : b['high'] - b['low'],\n",
    "            'bar4_range'     : range4,\n",
    "            'bar_num'        : num,\n",
    "            'fallback_reason': reason,\n",
    "        })\n",
    "\n",
    "    out = pd.DataFrame(records, index=bar4.index)\n",
    "    out = out[(out['sig_range'] > 0.5) & (out['sig_range'] < 500)]\n",
    "    return out\n",
    "\n",
    "\n",
    "asrs_signal_bars = select_asrs_signal_bars(dax5m)\n",
    "\n",
    "if asrs_signal_bars.empty:\n",
    "    print('No ASRS signal bars — collect 5-min data first (Cell 11a).')\n",
    "else:\n",
    "    n4 = (asrs_signal_bars['bar_num'] == 4).sum()\n",
    "    n5 = (asrs_signal_bars['bar_num'] == 5).sum()\n",
    "    print(f'ASRS signal bars: {len(asrs_signal_bars):,} days')\n",
    "    print(f'  4th bar selected : {n4:,} ({n4/len(asrs_signal_bars):.1%})')\n",
    "    print(f'  5th bar fallback : {n5:,} ({n5/len(asrs_signal_bars):.1%})')\n",
    "    print(f'\\nSignal bar range stats:')\n",
    "    print(asrs_signal_bars['sig_range'].describe().round(1))\n",
    "    print(f'\\nDate range: {asrs_signal_bars.index[0]} → {asrs_signal_bars.index[-1]}')\n",
    "    display(asrs_signal_bars.head())\n",
)

# ── Cell 33: Backtest engine ───────────────────────────────────────────────────
c33_md = md("## 11d. ASRS Backtest Engine\n")
c33 = code(
    "def simulate_asrs_day(day_bars, sig_high, sig_low):\n",
    "    \"\"\"\n",
    "    Simulate one ASRS trading day.\n",
    "\n",
    "    day_bars : 5-min bars starting after the signal bar closes (CET-indexed)\n",
    "    sig_high : signal bar high\n",
    "    sig_low  : signal bar low\n",
    "    Returns trade dict or None if no entry triggered.\n",
    "    \"\"\"\n",
    "    if day_bars.empty:\n",
    "        return None\n",
    "\n",
    "    entry_long  = sig_high + ASRS_ENTRY_BUFFER   # buy stop\n",
    "    entry_short = sig_low  - ASRS_ENTRY_BUFFER   # sell stop\n",
    "    # Stop loss = opposite order price\n",
    "    sl_long  = entry_short\n",
    "    sl_short = entry_long\n",
    "\n",
    "    direction   = None\n",
    "    entry_price = None\n",
    "    entry_time  = None\n",
    "\n",
    "    # Entry cutoff timestamp\n",
    "    cutoff = pd.Timestamp(\n",
    "        str(day_bars.index[0].date()) + ' ' + ASRS_ENTRY_CUTOFF,\n",
    "        tz=day_bars.index.tz,\n",
    "    )\n",
    "\n",
    "    # ── Phase 1: find first triggered stop order ──────────────\n",
    "    for ts, bar in day_bars.iterrows():\n",
    "        if direction is not None:\n",
    "            break\n",
    "        if ts > cutoff:\n",
    "            break  # past entry window\n",
    "\n",
    "        h, l = bar['high'], bar['low']\n",
    "        long_hit  = h >= entry_long\n",
    "        short_hit = l <= entry_short\n",
    "\n",
    "        if long_hit and short_hit:\n",
    "            if bar['open'] >= entry_long:\n",
    "                direction, entry_price = 'long',  entry_long\n",
    "            elif bar['open'] <= entry_short:\n",
    "                direction, entry_price = 'short', entry_short\n",
    "            else:\n",
    "                direction, entry_price = 'long',  entry_long  # tie-break → long\n",
    "            entry_time = ts\n",
    "        elif long_hit:\n",
    "            direction, entry_price, entry_time = 'long',  entry_long,  ts\n",
    "        elif short_hit:\n",
    "            direction, entry_price, entry_time = 'short', entry_short, ts\n",
    "\n",
    "    if direction is None:\n",
    "        return None\n",
    "\n",
    "    stop         = sl_long if direction == 'long' else sl_short\n",
    "    initial_risk = abs(entry_price - stop)\n",
    "\n",
    "    max_adverse  = 0.0\n",
    "    max_favorable = 0.0\n",
    "    exit_price   = None\n",
    "    exit_time    = None\n",
    "    exit_reason  = 'eod'\n",
    "\n",
    "    in_trade = day_bars[day_bars.index >= entry_time]\n",
    "\n",
    "    # ── Phase 2: manage open trade ────────────────────────────\n",
    "    for ts, bar in in_trade.iterrows():\n",
    "        h, l = bar['high'], bar['low']\n",
    "\n",
    "        if direction == 'long':\n",
    "            max_adverse   = max(max_adverse,   entry_price - l)\n",
    "            max_favorable = max(max_favorable, h - entry_price)\n",
    "            if l <= stop:\n",
    "                exit_price, exit_time, exit_reason = stop, ts, 'stop'\n",
    "                break\n",
    "        else:\n",
    "            max_adverse   = max(max_adverse,   h - entry_price)\n",
    "            max_favorable = max(max_favorable, entry_price - l)\n",
    "            if h >= stop:\n",
    "                exit_price, exit_time, exit_reason = stop, ts, 'stop'\n",
    "                break\n",
    "\n",
    "    if exit_price is None:\n",
    "        last = in_trade.iloc[-1]\n",
    "        exit_price, exit_time = last['close'], in_trade.index[-1]\n",
    "\n",
    "    pnl = (exit_price - entry_price) if direction == 'long' else (entry_price - exit_price)\n",
    "\n",
    "    return {\n",
    "        'direction'    : direction,\n",
    "        'entry_price'  : round(entry_price,   2),\n",
    "        'entry_time'   : entry_time,\n",
    "        'exit_price'   : round(exit_price,    2),\n",
    "        'exit_time'    : exit_time,\n",
    "        'exit_reason'  : exit_reason,\n",
    "        'stop'         : round(stop,           2),\n",
    "        'initial_risk' : round(initial_risk,   2),\n",
    "        'pnl'          : round(pnl,            2),\n",
    "        'max_adverse'  : round(max_adverse,    2),\n",
    "        'max_favorable': round(max_favorable,  2),\n",
    "        'sig_high'     : round(sig_high,       2),\n",
    "        'sig_low'      : round(sig_low,        2),\n",
    "        'sig_range'    : round(sig_high - sig_low, 2),\n",
    "        'entry_long'   : round(entry_long,     2),\n",
    "        'entry_short'  : round(entry_short,    2),\n",
    "    }\n",
    "\n",
    "\n",
    "print('simulate_asrs_day() defined.')\n",
)

# ── Cell 34: Run backtest ─────────────────────────────────────────────────────
c34 = code(
    "def run_asrs_backtest():\n",
    "    \"\"\"Run the full ASRS backtest over all signal bar days.\"\"\"\n",
    "    if asrs_signal_bars.empty:\n",
    "        print('No signal bars — collect 5-min data first.')\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    trades = []\n",
    "    for trade_date, sig in asrs_signal_bars.iterrows():\n",
    "        sig_high = sig['sig_high']\n",
    "        sig_low  = sig['sig_low']\n",
    "        bar_num  = sig['bar_num']\n",
    "\n",
    "        # Bars start after the signal bar closes\n",
    "        post_open = '09:20' if bar_num == 4 else '09:25'\n",
    "        day_start = pd.Timestamp(f'{trade_date} {post_open}', tz='Europe/Berlin')\n",
    "        day_end   = pd.Timestamp(f'{trade_date} {ASRS_EOD_EXIT}', tz='Europe/Berlin')\n",
    "\n",
    "        day_bars = dax5m.loc[day_start:day_end]\n",
    "        if len(day_bars) < 2:\n",
    "            continue\n",
    "\n",
    "        result = simulate_asrs_day(day_bars, sig_high, sig_low)\n",
    "        if result is not None:\n",
    "            result['trade_date']      = pd.Timestamp(str(trade_date))\n",
    "            result['bar_num']         = bar_num\n",
    "            result['fallback_reason'] = sig['fallback_reason']\n",
    "            trades.append(result)\n",
    "\n",
    "    if not trades:\n",
    "        return pd.DataFrame()\n",
    "    df = pd.DataFrame(trades).set_index('trade_date').sort_index()\n",
    "    return df\n",
    "\n",
    "\n",
    "if not asrs_signal_bars.empty and dax5m is not None:\n",
    "    df_asrs = run_asrs_backtest()\n",
    "    print(f'ASRS backtest complete: {len(df_asrs):,} trades')\n",
    "    if not df_asrs.empty:\n",
    "        n_win  = (df_asrs['pnl'] > 0).sum()\n",
    "        n_loss = (df_asrs['pnl'] < 0).sum()\n",
    "        n_flat = (df_asrs['pnl'] == 0).sum()\n",
    "        total  = df_asrs['pnl'].sum()\n",
    "        print(f'  Winners: {n_win} | Losers: {n_loss} | Flat: {n_flat}')\n",
    "        print(f'  Total PnL: {total:.1f} pts  (~€{total*25:,.0f} per contract)')\n",
    "        display(df_asrs.tail())\n",
    "else:\n",
    "    df_asrs = pd.DataFrame()\n",
    "    print('Skipped — no data or signal bars.')\n",
)

# ── Cell 35: Performance metrics ─────────────────────────────────────────────
c35_md = md("## 11e. ASRS Performance Metrics\n")
c35 = code(
    "if df_asrs.empty:\n",
    "    print('No ASRS trades to analyse.')\n",
    "else:\n",
    "    # Adapt df_asrs for compute_metrics (expects pnl_total, added, units columns)\n",
    "    _df = df_asrs.copy()\n",
    "    _df['pnl_total'] = _df['pnl']\n",
    "    _df['added']     = False\n",
    "    _df['units']     = 1\n",
    "    _df['sl_type']   = 'ASRS'\n",
    "    _df['use_add']   = False\n",
    "\n",
    "    m = compute_metrics(_df, label='ASRS')\n",
    "\n",
    "    print('=' * 55)\n",
    "    print('  Advanced School Run Strategy — Performance Summary')\n",
    "    print('=' * 55)\n",
    "    print(f'  Trades          : {m[\"n_trades\"]}')\n",
    "    print(f'  Win rate        : {m[\"win_rate_%\"]:.1f}%  '\n",
    "          f'(L {m[\"wr_long_%\"]:.1f}% | S {m[\"wr_short_%\"]:.1f}%)')\n",
    "    print(f'  Avg winner      : +{m[\"avg_win_pts\"]:.1f} pts')\n",
    "    print(f'  Avg loser       : {m[\"avg_loss_pts\"]:.1f} pts')\n",
    "    print(f'  Win/Loss ratio  : {m[\"win_loss_ratio\"]:.2f}x')\n",
    "    print(f'  Profit factor   : {m[\"profit_factor\"]:.2f}')\n",
    "    print(f'  Total PnL       : {m[\"total_pnl_pts\"]:.0f} pts  '\n",
    "          f'(~€{m[\"total_pnl_pts\"]*25:,.0f} per contract)')\n",
    "    print(f'  Sharpe ratio    : {m[\"sharpe\"]:.2f}')\n",
    "    print(f'  Max drawdown    : {m[\"max_dd_pts\"]:.0f} pts')\n",
    "    print(f'  Stopped out     : {m[\"n_stopped\"]:,} | EOD exit: {m[\"n_eod\"]:,}')\n",
    "    print(f'  Longs           : {m[\"n_longs\"]} | Shorts: {m[\"n_shorts\"]}')\n",
    "    print()\n",
    "\n",
    "    # 4th vs 5th bar comparison\n",
    "    grp4 = df_asrs[df_asrs['bar_num'] == 4]\n",
    "    grp5 = df_asrs[df_asrs['bar_num'] == 5]\n",
    "    print('  --- Signal bar selection split ---')\n",
    "    for lbl, grp in [('4th bar', grp4), ('5th bar (fallback)', grp5)]:\n",
    "        if len(grp):\n",
    "            wr = (grp['pnl'] > 0).mean() * 100\n",
    "            print(f'  {lbl:20s}: {len(grp):>4} trades | WR {wr:.1f}% | avg pnl {grp[\"pnl\"].mean():.1f} pts')\n",
)

# ── Cell 36: Equity curve chart ───────────────────────────────────────────────
c36_md = md("## 11f. ASRS Equity Curve & Annual Breakdown\n")
c36 = code(
    "if df_asrs.empty:\n",
    "    print('No ASRS trades to plot.')\n",
    "else:\n",
    "    fig, axes = plt.subplots(3, 1, figsize=(14, 12))\n",
    "    fig.suptitle('Advanced School Run Strategy — Equity & Analytics',\n",
    "                 fontsize=14, fontweight='bold')\n",
    "\n",
    "    # Equity curve\n",
    "    cum = df_asrs['pnl'].cumsum()\n",
    "    ax = axes[0]\n",
    "    ax.plot(cum.index, cum.values, color='steelblue', lw=1.5)\n",
    "    ax.axhline(0, color='black', lw=0.7, ls='--')\n",
    "    ax.fill_between(cum.index, cum.values, 0,\n",
    "                    where=cum.values >= 0, alpha=0.15, color='green')\n",
    "    ax.fill_between(cum.index, cum.values, 0,\n",
    "                    where=cum.values < 0,  alpha=0.15, color='red')\n",
    "    ax.set_title('Cumulative PnL (points)')\n",
    "    ax.set_ylabel('Points')\n",
    "    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'{x:,.0f}'))\n",
    "\n",
    "    # Annual bar chart\n",
    "    annual = df_asrs.groupby(df_asrs.index.year)['pnl'].sum()\n",
    "    colors = ['green' if v >= 0 else 'red' for v in annual.values]\n",
    "    ax2 = axes[1]\n",
    "    ax2.bar(annual.index, annual.values, color=colors, alpha=0.75,\n",
    "            edgecolor='black', lw=0.5)\n",
    "    ax2.axhline(0, color='black', lw=0.7)\n",
    "    ax2.set_title('Annual PnL (points)')\n",
    "    ax2.set_ylabel('Points')\n",
    "    for yr, val in zip(annual.index, annual.values):\n",
    "        offset = 20 if val >= 0 else -50\n",
    "        ax2.text(yr, val + offset, f'{val:,.0f}', ha='center', fontsize=8)\n",
    "\n",
    "    # Long vs short equity\n",
    "    longs  = df_asrs[df_asrs['direction'] == 'long']['pnl'].cumsum()\n",
    "    shorts = df_asrs[df_asrs['direction'] == 'short']['pnl'].cumsum()\n",
    "    ax3 = axes[2]\n",
    "    ax3.plot(longs.index,  longs.values,  color='green', lw=1.2, label='Longs')\n",
    "    ax3.plot(shorts.index, shorts.values, color='red',   lw=1.2, label='Shorts')\n",
    "    ax3.axhline(0, color='black', lw=0.7, ls='--')\n",
    "    ax3.set_title('Cumulative PnL by Direction')\n",
    "    ax3.set_ylabel('Points')\n",
    "    ax3.legend()\n",
    "\n",
    "    plt.tight_layout()\n",
    "    out_path = ROOT / 'data' / 'asrs_equity.png'\n",
    "    fig.savefig(out_path, dpi=150, bbox_inches='tight')\n",
    "    plt.show()\n",
    "    print(f'Saved → {out_path.name}')\n",
)

# ── Cell 37: Signal bar analytics ────────────────────────────────────────────
c37_md = md("## 11g. ASRS Signal Bar & Day-of-Week Analytics\n")
c37 = code(
    "if df_asrs.empty:\n",
    "    print('No ASRS trades to analyse.')\n",
    "else:\n",
    "    # Bar range buckets\n",
    "    df_asrs['range_bucket'] = pd.cut(\n",
    "        df_asrs['sig_range'],\n",
    "        bins=[0, 15, 25, 40, 60, 80, 500],\n",
    "        labels=['<15', '15-25', '25-40', '40-60', '60-80', '80+'],\n",
    "    )\n",
    "    bucket = df_asrs.groupby('range_bucket', observed=True).agg(\n",
    "        trades    = ('pnl', 'count'),\n",
    "        win_rate  = ('pnl', lambda x: (x > 0).mean() * 100),\n",
    "        avg_pnl   = ('pnl', 'mean'),\n",
    "        total_pnl = ('pnl', 'sum'),\n",
    "    ).round(1)\n",
    "    print('=== ASRS: Signal Bar Range vs Outcome ===')\n",
    "    print(bucket.to_string())\n",
    "    print()\n",
    "\n",
    "    # Day of week\n",
    "    dow_map = {0: 'Mon', 1: 'Tue', 2: 'Wed', 3: 'Thu', 4: 'Fri'}\n",
    "    df_asrs['dow'] = pd.to_datetime(df_asrs.index).dayofweek\n",
    "    dow = df_asrs.groupby('dow').agg(\n",
    "        trades    = ('pnl', 'count'),\n",
    "        win_rate  = ('pnl', lambda x: (x > 0).mean() * 100),\n",
    "        avg_pnl   = ('pnl', 'mean'),\n",
    "        total_pnl = ('pnl', 'sum'),\n",
    "    ).round(1)\n",
    "    dow.index = [dow_map[i] for i in dow.index]\n",
    "    print('=== ASRS: Day-of-Week Breakdown ===')\n",
    "    print(dow.to_string())\n",
    "    print()\n",
    "\n",
    "    # Export trades\n",
    "    out_path = ROOT / 'data' / 'asrs_trades.csv'\n",
    "    df_asrs.to_csv(out_path)\n",
    "    print(f'Trades exported → {out_path.name}')\n",
)

# ── Append all cells ──────────────────────────────────────────────────────────
new_cells = [
    c29, c30, c31_md, c31, c32_md, c32, c33_md, c33, c34, c35_md, c35,
    c36_md, c36, c37_md, c37,
]

nb["cells"].extend(new_cells)

with open(NB_PATH, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print(f"Done. Notebook now has {len(nb['cells'])} cells.")
